# Generated by Django 4.0 on 2022-03-02 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='myquery',
            field=models.TextField(max_length=200),
        ),
    ]
