# Generated by Django 4.0 on 2022-03-02 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_project', '0002_alter_response_myquery'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('myquery', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='response',
            name='myquery',
            field=models.TextField(),
        ),
    ]
