# Generated by Django 4.0 on 2022-03-02 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_project', '0003_topic_alter_response_myquery'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Topic',
        ),
        migrations.RenameField(
            model_name='response',
            old_name='myquery',
            new_name='text',
        ),
    ]
